spring.application.name=todo-list

# Configure MySQL Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/todo-list?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==============================
# JWT
# ==============================
jwt.secret=MyVerySecretKeyForTodoApplicationJwtAuthentication2026SecureKey

# 1 hour
jwt.expiration=86400000

# Logging
logging.level.todolist=DEBUG
logging.level.org.springframework.web=DEBUG
