spring.application.name=todo-list

# Configure MySQL Database Connection

spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==============================
# JWT
# ==============================
jwt.secret=${JWT_SECRET}

# 1 hour
jwt.expiration=36000

# Logging
logging.level.todolist=DEBUG
logging.level.org.springframework.web=DEBUG
